export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE = "UPDATE_TASKS_FAILURE";

export const ADD_SUB_TASK_REQUEST = "ADD_SUB_TASK_REQUEST";
export const ADD_SUB_TASK_SUCCESS = "ADD_SUB_TASK_SUCCESS";
export const ADD_SUB_TASK_FAILURE = "ADD_SUB_TASK_FAILURE";

export const DELETE_SUB_TASK_REQUEST = "DELETE_SUB_TASK_REQUEST";
export const DELETE_SUB_TASK_SUCCESS = "DELETE_SUB_TASK_SUCCESS";
export const DELETE_SUB_TASK_FAILURE = "DELETE_SUB_TASK_FAILURE";
